### PR TITLE
Changed/added some options

### PR DESCRIPTION
**Pull request by Epikem**
Added or changed some options because I think seems convenient to use. I test some but it may need
 more test/discuss.
* support escape string : can use like below
`#[pypre]#ifdef debug`
`#@ifdef debug`

* split mode to multiple options : can customize run flow more freely.

* added read, write encoding

### CODE REVIEW

**Comment by evanplaice** [comment]
Interesting addition. Currently you should be able to comment out directives using a second hash. What's the benefit to using this approach? How does this compare to typical useage pattern in C preprocessor code? 

I'll take a closer look at the rest. The modes were added by another dev. If we change them, they'll likely break code for people who use them. When API changes (not incl additions) occur, it's preferred to provide a wrapper + deprecation message for existing users. Or to just push a major version to indicate a break.

Give me a few and and I'll take a closer look.

**Comment by Epikem** [comment]
Right I forgot of deprecation etc.. I changed to 'escape' because I had some commented '#else:' python statement and that made error or made problem when i use find and replace etc... I thought it is better because C uses '#' to preprocessor and uses '//' to comment so there is no conflict. But that could be not that important if someone don't keep commented code much. I'll remove this if you think its not important.

What I think more important is run mode. I split mode to three options because using mode is restrictive . I think I could add wrapper for mode and escapeChar easily (map mode to matching three options, map escapeChar to escape).

**Comment by evanplaice** [comment]
So, the default escape char is now # and configurable? If so, good to go.

-----

Why the version bump. I'd prefer to manage those. This will be a feature release so I'll publish it as .8 as soon as you've finished this PR.

-----

Can't say I'm a fan of multiple input spellings

```python
if self.mode == 'RUN' or self.mode == 'run' or self.mode == 'Run':
```

Correct me if I'm wrong but you're trying to clean up some of the API mess from the original implementation. Good call there but instead of checking for multiple patterns, just convert them to lowercase before comparing.

```python
if self.mode.lower() == 'run':
``` 

-----

I like the encoding addition, good call there.

----

How does exec running in global work. I'm not familiar with how that works? The import semantics that make this self-consuming are very strange. I just want to make sure existing functionality doesn't get broken.

----

Feel free to add your name to the license and as a co-author in the main source. Apologies if I come off as nit-picky. Just trying to sustain a high degree of quality.

**Comment by Epikem** [comment]
No that was my mistake. Forgot that compatibility is very important. I added check_deprecation function. Thank you!

**Comment by evanplaice** [comment]
LGTM. Nice work.

**Pull request merged**
